version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: minhgiang_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minhgiang_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      # Script tự chạy khi db được tạo lần đầu
      - ./infrastructure/database:/docker-entrypoint-initdb.d/
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: minhgiang_rabbitmq
    ports:
      - "5672:5672"   # Port giao tiếp MQTT cho code
      - "15672:15672" # Port Management UI trên Web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: unless-stopped

volumes:
  db-data:
